// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import("./components/Avatar.vue")["default"]
    DeleteButton: typeof import("./components/buttons/DeleteButton.vue")["default"]
    DropDown: typeof import("./components/buttons/DropDown.vue")["default"]
    FabButton: typeof import("./components/buttons/FabButton.vue")["default"]
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoaderButton: typeof import("./components/buttons/LoaderButton.vue")["default"]
    MakdownEditor: typeof import("./components/MakdownEditor.vue")["default"]
    OptionLocales: typeof import("./components/OptionLocales.vue")["default"]
    PaymentButton: typeof import("./components/buttons/PaymentButton.vue")["default"]
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendButton: typeof import("./components/buttons/SendButton.vue")["default"]
    ThemeButton: typeof import("./components/buttons/ThemeButton.vue")["default"]
    ToggleTheme: typeof import("./components/ToggleTheme.vue")["default"]
    TranslationComponent: typeof import("./components/TranslationComponent.vue")["default"]
  }
}
