// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import("./components/Avatar.vue")["default"]
    BarUp: typeof import('./components/TabHeader/BarUp.vue')['default']
    Button: typeof import('./components/CarouselForCertifications/ButtonForCertification/Button.vue')['default']
    ButtonsAtendimentoRh: typeof import('./components/Carousel/ControlsCarousel/ButtonsAtendimentoRh.vue')['default']
    Card: typeof import('./components/CardForDocSIG/Card.vue')['default']
    CardRhDIvulga: typeof import('./components/CardForRhDivulga/CardRhDIvulga.vue')['default']
    CardSeeMore: typeof import('./components/PageSeeMore/CardSeeMore.vue')['default']
    Carousel: typeof import('./components/Carousel/Carousel.vue')['default']
    CarouselAtendimentoRh: typeof import('./components/Carousel/CarouselAtendimentoRh.vue')['default']
    CarouselCertifications: typeof import('./components/CarouselForCertifications/CarouselCertifications.vue')['default']
    DeleteButton: typeof import("./components/buttons/DeleteButton.vue")["default"]
    DialogAddRamal: typeof import('./components/Pages/PageRamais/AddRamal/DialogAddRamal.vue')['default']
    DropDown: typeof import("./components/buttons/DropDown.vue")["default"]
    ExTable: typeof import('./components/TableRamais/exTable.vue')['default']
    FabButton: typeof import("./components/buttons/FabButton.vue")["default"]
    HeaderRamais: typeof import('./components/TableRamais/TabOfTableRamais/HeaderRamais.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImageRh: typeof import('./components/Image/ImageRh.vue')['default']
    Input: typeof import('./components/Input/Input.vue')['default']
    Item: typeof import('./components/Item/Item.vue')['default']
    List: typeof import('./components/CardForDocSIG/listForCard/List.vue')['default']
    LoaderButton: typeof import("./components/buttons/LoaderButton.vue")["default"]
    Login: typeof import('./components/Login/Login.vue')['default']
    MakdownEditor: typeof import("./components/MakdownEditor.vue")["default"]
    OptionLocales: typeof import("./components/OptionLocales.vue")["default"]
    PageLogin: typeof import('./components/login/PageLogin.vue')['default']
    Pagination: typeof import('./components/Pagination/Pagination.vue')['default']
    PaymentButton: typeof import("./components/buttons/PaymentButton.vue")["default"]
    PRamais: typeof import('./components/Pages/PageRamais/PRamais.vue')['default']
    PRhDivulga: typeof import('./components/Pages/RhDivulga/PRhDivulga.vue')['default']
    PSeeMore: typeof import('./components/Pages/PageSeeMoreCard/PSeeMore.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendButton: typeof import("./components/buttons/SendButton.vue")["default"]
    Separator: typeof import('./components/Separator/Separator.vue')['default']
    SeparatorForEmergence: typeof import('./components/TableRamais/SeparatorForEmergence.vue')['default']
    Tab: typeof import('./components/CardForDocSIG/TabForCard/Tab.vue')['default']
    Table: typeof import('./components/TableRamais/Table.vue')['default']
    ThemeButton: typeof import("./components/buttons/ThemeButton.vue")["default"]
    ToggleTheme: typeof import("./components/ToggleTheme.vue")["default"]
    TranslationComponent: typeof import("./components/TranslationComponent.vue")["default"]
  }
}
